
-- =========================================================
-- WMPS - MASTER DATABASE SCHEMA & SECURITY (OPERACAO VACUO ZERO)
-- =========================================================

-- 1. TABELA DE ATLETAS (PERFIS)
CREATE TABLE IF NOT EXISTS atletas (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  phone TEXT,
  role TEXT DEFAULT 'athlete',
  birth_date DATE,
  gender TEXT,
  cpf TEXT,
  height FLOAT,
  weight FLOAT,
  goal TEXT,
  sport TEXT,
  photo_url TEXT,
  must_change_password BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA DE ANAMNESE
CREATE TABLE IF NOT EXISTS anamnese (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE,
  athlete_name TEXT,
  date DATE DEFAULT CURRENT_DATE,
  data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABELA DE BEM-ESTAR (WELLNESS)
CREATE TABLE IF NOT EXISTS bem_estar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE,
  athlete_name TEXT,
  date DATE DEFAULT CURRENT_DATE,
  recovery INTEGER,
  sleep INTEGER,
  stress INTEGER,
  fatigue INTEGER,
  soreness INTEGER,
  score INTEGER,
  classification TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABELA DE CICLO MENSTRUAL
CREATE TABLE IF NOT EXISTS ciclo_menstrual (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE UNIQUE,
  last_period_date DATE,
  cycle_duration INTEGER DEFAULT 28,
  regular BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABELA DE SINTOMAS MENSTRUAIS
CREATE TABLE IF NOT EXISTS sintomas_menstruais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE,
  date DATE DEFAULT CURRENT_DATE,
  fatigue INTEGER,
  pain INTEGER,
  bloating INTEGER,
  mood INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABELA DE PRONTIDÃO (READINESS SCORE)
CREATE TABLE IF NOT EXISTS prontidao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE,
  date DATE DEFAULT CURRENT_DATE,
  score INTEGER,
  data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(athlete_id, date)
);

-- 7. TABELA DE COMORBIDADES (PERFIL CLÍNICO)
CREATE TABLE IF NOT EXISTS comorbidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE UNIQUE,
  has_diabetes BOOLEAN DEFAULT FALSE,
  has_hypertension BOOLEAN DEFAULT FALSE,
  has_cardiac BOOLEAN DEFAULT FALSE,
  has_orthopedic BOOLEAN DEFAULT FALSE,
  medications TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. TABELA DE REGISTROS CLÍNICOS (MONITORAMENTO DIÁRIO)
CREATE TABLE IF NOT EXISTS registros_clinicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE,
  date DATE DEFAULT CURRENT_DATE,
  glucose_pre INTEGER,
  glucose_post INTEGER,
  glucose_fasting INTEGER,
  bp_sys INTEGER,
  bp_dia INTEGER,
  med_adherence BOOLEAN DEFAULT TRUE,
  symptoms TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. TABELA DE TREINOS (PRESCRIÇÕES)
CREATE TABLE IF NOT EXISTS treinos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE,
  coach_id UUID,
  athlete_name TEXT,
  status TEXT DEFAULT 'pending',
  data JSONB,
  completed_at TIMESTAMPTZ,
  completed_blocks INTEGER,
  total_blocks INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. TABELA DE SESSÕES DE TREINO (HISTÓRICO)
CREATE TABLE IF NOT EXISTS sessoes_treino (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE,
  athlete_name TEXT,
  date DATE DEFAULT CURRENT_DATE,
  rpe INTEGER,
  duration INTEGER,
  load INTEGER,
  distance FLOAT DEFAULT 0,
  volume FLOAT DEFAULT 0,
  series INTEGER DEFAULT 0,
  reps INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. TABELA DE AVALIAÇÕES FÍSICAS
CREATE TABLE IF NOT EXISTS avaliacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  athlete_id UUID REFERENCES atletas(id) ON DELETE CASCADE,
  athlete_name TEXT,
  type TEXT,
  date DATE DEFAULT CURRENT_DATE,
  data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- CONFIGURAÇÃO DE SEGURANÇA (RLS)
-- =========================================================

-- Habilitar RLS em todas as tabelas
ALTER TABLE atletas ENABLE ROW LEVEL SECURITY;
ALTER TABLE anamnese ENABLE ROW LEVEL SECURITY;
ALTER TABLE bem_estar ENABLE ROW LEVEL SECURITY;
ALTER TABLE ciclo_menstrual ENABLE ROW LEVEL SECURITY;
ALTER TABLE sintomas_menstruais ENABLE ROW LEVEL SECURITY;
ALTER TABLE prontidao ENABLE ROW LEVEL SECURITY;
ALTER TABLE comorbidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE registros_clinicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE treinos ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessoes_treino ENABLE ROW LEVEL SECURITY;
ALTER TABLE avaliacoes ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS: Atleta acessa apenas seus próprios dados
DO $$ 
DECLARE 
  t text;
BEGIN
  FOR t IN SELECT table_name 
           FROM information_schema.tables 
           WHERE table_schema = 'public' 
           AND table_name IN ('anamnese', 'bem_estar', 'ciclo_menstrual', 'sintomas_menstruais', 'prontidao', 'comorbidades', 'registros_clinicos', 'treinos', 'sessoes_treino', 'avaliacoes')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Atletas acessam seus próprios dados" ON %I', t);
    EXECUTE format('CREATE POLICY "Atletas acessam seus próprios dados" ON %I FOR ALL USING (auth.uid() = athlete_id)', t);
  END LOOP;
END $$;

-- POLÍTICA ESPECIAL PARA TABELA ATLETAS
DROP POLICY IF EXISTS "Atletas acessam seu proprio perfil" ON atletas;
CREATE POLICY "Atletas acessam seu proprio perfil" ON atletas FOR ALL USING (auth.uid() = id);

-- POLÍTICA PARA COACH (Acesso Global para leitura)
-- Nota: Em produção real, você deve filtrar por coach_id se houver múltiplos treinadores.
DROP POLICY IF EXISTS "Coaches acessam tudo" ON atletas;
-- CREATE POLICY "Coaches acessam tudo" ON atletas FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

-- ÍNDICES DE PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_anamnese_athlete ON anamnese(athlete_id);
CREATE INDEX IF NOT EXISTS idx_bem_estar_athlete ON bem_estar(athlete_id);
CREATE INDEX IF NOT EXISTS idx_prontidao_athlete ON prontidao(athlete_id);
CREATE INDEX IF NOT EXISTS idx_registros_clinicos_athlete ON registros_clinicos(athlete_id);
CREATE INDEX IF NOT EXISTS idx_treinos_athlete ON treinos(athlete_id);
CREATE INDEX IF NOT EXISTS idx_sessoes_treino_athlete ON sessoes_treino(athlete_id);
